### ISSUE TITLE
API Improvements

### ISSUE THREAD

**Issue by connorshea** [connorshea/VideoGameList#735]
- [x] Add support for API Tokens. (#883)
- [ ] Provide GraphiQL in production.
- [x] Improve `API.md` documentation to properly explain the process for creating OAuth applications. (#823)
- [x] Provide more example GraphQL queries.
- [ ] Add rate limiting.
- [x] Add pagination. (#760)
- [x] Add Events to the API. (#747)
- [x] Make ActiveStorage attachment URLs accessible via the API.
- [x] Add mutations to the API. (#757)
- [x] Update graphql-ruby so we can use the native Date type for Release Dates and Start/Completion Dates.
- [x] Improve test coverage of OAuth functionality and GraphQL endpoints. (#738)
- [x] Make GraphiQL not give a meaningless error if you're not logged in.
- [x] Add a link to the API docs in the user dropdown.
- [x] Add Steam AppIDs to games. (#791)
- [x] Explain mutations in the API docs.
- [x] Figure out how to get the API to return valid total and hasNextPage data for the pageInfo. (#861)
- [x] Make read/write scopes relevant in the API. Currently they're unchecked for mutations. (#823)
- [x] Add queries like 'Games' that list all the games on the site. (#761)
- [x] Add a 'perPage' field to pageInfo. (#861)
- [x] Add a mutation for `updateGameInLibrary`. (#859)

**Comment by connorshea** [comment]
Moved the last two items into separate issues #1017 #1018.
